### ISSUE TITLE
path.join(__dirname, 'node_modules', '.bin') is not a great pattern to recommend

### ISSUE THREAD

**Issue by timoxley** [vesln/nixt#11]
Just FYI, this example out of the readme is brittle/bad practice:

```js
path.join(__dirname, 'node_modules', '.bin')
```
While this works *most* of the time, the location isn't *guaranteed* to contain the executables you want in the case that you're not the top-level package and npm has deduped your executable higher in the node_modules tree. This is going to occur a lot more once the "maximally flat" install algorithm lands in npm 3.0.0.

It's probably not a big deal since nixt probably used mostly as a devDependency and as a top-level package, plus it's probably outside of nixt's responsibilities, but just thinking nixt should probably avoid advocating this method and could perhaps recommend/embed something like https://www.npmjs.com/npm-path which gives you the value of the augmented `$PATH` you'd get in an npm script.

**Comment by eush77** [comment]
That example is featuring `.cwd` method so `npm-path` is not really relevant :wink: 

On the other hand, something like

```js
var which = require('npm-which');

nixt()
.cwd(path.dirname(which.sync('mocha', { cwd: __dirname })))
.run('mocha --version')
.stdout('1.13.0')
.end();
```

while techically correct, seems to be too far from the point.

Maybe it's better to just change the example to something radically simpler:

```js
nixt()
.cwd(__dirname)
.run('pwd')
.stdout(/test$/)
.end();
```

@vesln, do you have any opinion on this?

**Comment by vesln** [comment]
i have no preferences really, as long as we keep it easy to grasp

**Comment by eush77** [comment]
It's decided then. I changed these examples in 57cd5ad.
