### ISSUE TITLE
Standard input without prompt?

### ISSUE THREAD

**Issue by kemitchell** [vesln/nixt#12]
Forgive me if I've missed documentation or a code comment, but how does one simulate something like the following with nixt?

```shellsession
$ cat some-input | my-program
$ my-program < some-input
```

I see `.on(prompt).respond(...)`, but no option for input on `stdin` that doesn't respond to a prompt.

Many thanks!

**Comment by vesln** [comment]
@kemitchell just added you as a collaborator, feel free to implement whatever will suit your needs. Just open a PR first. Thanks!
